// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageLibrary;

#nullable disable

namespace StorageLibrary.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ModelLibrary.Die.FavoredDie", b =>
                {
                    b.Property<int>("favoredDieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("FavoredDieId");

                    b.Property<byte>("favorFactor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FavorFactor");

                    b.Property<byte>("favoredFace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FavoredFace");

                    b.HasKey("favoredDieId");

                    b.ToTable("FavoredDie");
                });

            modelBuilder.Entity("ModelLibrary.Result.FavoredResultPair", b =>
                {
                    b.Property<int>("favoredResultPairId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("FavoredResultPairId");

                    b.Property<int>("FirstFavoredDieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SecondFavoredDieId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("face")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FirstFace");

                    b.Property<byte>("secondFace")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SecondFace");

                    b.HasKey("favoredResultPairId");

                    b.HasIndex("FirstFavoredDieId");

                    b.HasIndex("SecondFavoredDieId");

                    b.ToTable("FavoredResultPair");
                });

            modelBuilder.Entity("ModelLibrary.Result.FavoredResultPair", b =>
                {
                    b.HasOne("ModelLibrary.Die.FavoredDie", "FirstFavoredDie")
                        .WithMany("FirstFavoredResultPairCollection")
                        .HasForeignKey("FirstFavoredDieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ModelLibrary.Die.FavoredDie", "SecondFavoredDie")
                        .WithMany("SecondFavoredResultPairCollection")
                        .HasForeignKey("SecondFavoredDieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FirstFavoredDie");

                    b.Navigation("SecondFavoredDie");
                });

            modelBuilder.Entity("ModelLibrary.Die.FavoredDie", b =>
                {
                    b.Navigation("FirstFavoredResultPairCollection");

                    b.Navigation("SecondFavoredResultPairCollection");
                });
#pragma warning restore 612, 618
        }
    }
}
