// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StorageLibrary;

#nullable disable

namespace StorageLibrary.Migrations
{
    [DbContext(typeof(DbContext))]
    partial class DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("ModelLibrary.Die.FavoredDie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FavorFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FavoredFace")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FavoredDie");
                });
#pragma warning restore 612, 618
        }
    }
}
