// <auto-generated />
using MVCViewProject.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVCViewProject.Storage
{
    [DbContext(typeof(DbContext))]
    [Migration("20230902200242_migration01")]
    partial class migration01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("MVCViewProject.Models.PairRoll", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FirstFavorFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FirstFavoredFace")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("FirstUpFace")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SecondFavorFactor")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SecondFavoredFace")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SecondUpFace")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PairRoll");
                });
#pragma warning restore 612, 618
        }
    }
}
